spring:
  application:
    name: apigateway
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://172.18.0.15:8761/eureka}
      registerWithEureka: true
      fetchRegistry: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id}
